name: analytics-worker

on:
  push:
    branches:
      - main
      - feature/*:
        branches:
          - main
  pull_request:
    branches:
      - main
      - feature/*:
        branches:
          - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run echo
        run: echo "Hello from analytics-worker"